site_name: Retouched Documentation
site_url: https://retouched-project.github.io/docs/
site_description: Open-source reimplementation of Nitrome Touchy and Brass Monkey
site_dir: site

docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: orange
  logo: assets/retouched_logo.svg
  favicon: assets/retouched_logo.svg
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
